before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: E/DihTqQ/c0A+7ZqZ3Dvwgq5pjZY3GGlxobvCVdTrSERvKFiSlh2Oirt8St6pzzh9ywDVm9C1JGAQmspYzCUFoTY7nGA3uSvJ1eYAkcRsIqtUNvKXGY8exokd7kbgckHRWSZ1aWyokcgCrT+2cmrMo0BS0vpiiklZJcmSz/l+cC5G4v7yr1CQ3H59jWu5Vs5UgoQN0p7Iu0RADV9z8Y2pTSjJGAXGS3r/QjjXvWC1oWmNRQ/qdYW4aRrEDKnEpdiad0MIDwX6+b4FBRRlL9mTnijN50U2RrNduH7W7PG6WuKM8XO0J/r+ZFQyzz/c55SfxuQEhxYp5GI816NaXGNPSZNxyAtvYJ95AqV9iedn3LF3jLz2tMkvMHCYIFmHcOHTpFQBqhBQLAB5kDTkBTYRv27sapMpINqznytaG33XmzXhCttm/qlr6w48kqeZewbzQywyNQMQu9PMGZtz6fYUuuWPwY2l2JxpYA8hwcLEHSgeGTBw+iz4ocGIuM/Eh7GX25gIgoa9p/tyCB+eqBU34d173ySvV08uNCSeI9FSKulLEb/DR2kjS6OG0wyZZg/V5G2l0G9PmvtX52fSKEHxQ0M6VwfDUG71dogqlLiUUHPlshmkBv+mu1t4CAbHyU+ty4DfLZ+eGM3yzMDti2AZ1fLzBWYubySxtRSxAEHRTk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
